version: 2.1
orbs:
  node: circleci/node@4.7.0

jobs:
  build:
    executor:
      name: node/default
      tag: '16.11.1'
    steps:
      - checkout
      - node/install-packages
      - run:
          name: .env.production creating
          command: |
            touch .env.production
            echo "CONTENTFUL_SPACE_ID=$CONTENTFUL_SPACE_ID" > .env.production
            echo "CONTENTFUL_ACCESS_TOKEN=$CONTENTFUL_ACCESS_TOKEN" > .env.production
      - run: npm run build
      - run:
          name: Deploying
          command: node ./.circleci/ftp-deploy.js $FTP_ADDRESS $FTP_USER $FTP_PASSWORD
  
workflows:
  version: 2
  main:
    jobs:
      - build:
          filters:
            branches:
              only: main