name: Build and deploy - Wroconsult App
on:
    push:
      branches: [main]
    workflow_dispatch:

jobs:
    build:
      name: Build ⛏
      runs-on: ubuntu-latest
      steps:
        - name: Checkout repository
          uses: actions/checkout@main
        - name: Install dependencies
          run: npm ci
        - name: Build dependencies
          run: npm run build
        - name: Archive production artifact
          uses: actions/upload-artifact@main
          with:
              name: public
              path: public
    deploy:
        name: Deploy 🚀
        needs: build
        runs-on: ubuntu-latest
    steps: 
        - name: Checkout repository
          uses: actions/checkout@main
        - name: Download artifact
          uses: actions/download-artifact@main
          with: 
              name: public
              path: public
        - name: FTP Deploy
        # You may pin to the exact commit or the version.
        # uses: SamKirkland/FTP-Deploy-Action@d2724c6194d42ae5d4d042070d51d23cbc6ad83f
          uses: SamKirkland/FTP-Deploy-Action@4.1.0
          with:
          # ftp server
              server: ${{ secrets.FTP_HOST }}
          # ftp username
              username: ${{ secrets.FTP_USER }}
          # ftp password
              password: ${{ secrets.FTP_PASSWORD }}
          # Server port to connect to (read your web hosts docs)
              port: 21
          # protocol to deploy with - ftp, ftps, or ftps-legacy
          #protocol: # optional
          # Folder to upload from, must end with trailing slash /
              local-dir: public/
          # Path to upload to on the server. Must end with trailing slash /
          #server-dir: # optional
          # Path and name of the state file - this file is used to track which files have been deployed
          #state-name: # optional
          # Prints which modifications will be made with current config options, but doesnt actually make any changes
          #dry-run: # optional
          # Deletes ALL contents of server-dir, even items in excluded with exclude argument
          #dangerous-clean-slate: # optional
          # An array of glob patterns, these files will not be included in the publish/delete process
          #exclude:
          # How verbose should the information be - minimal, standard, or verbose
          #log-level: # optional
          # strict or loose
          #security: # optional