version: 2.1
orbs:
  node: circleci/node@4.7.0

jobs:
  build-deploy:
    executor:
      name: node/default
      tag: '16.11.1'
    steps:
      - checkout
      - node/install-packages
      - run: npm run build
      - run:
          name: Deploying
          command: node ./.circleci/ftp-deploy.js $FTP_ADDRESS $FTP_USER $FTP_PASSWORD
      - run:
          name: Notify DatoCMS about the status of the job
          command: 'curl -X POST --data-binary "{\"payload\": { \"branch\": \"$CIRCLE_BRANCH\", \"status\": \"failed\" } }" https://webhooks.datocms.com/1cd0c86d1a/deploy-results'
          when: on_fail
      - run:
          name: Notify DatoCMS about the status of the job
          command: 'curl -X POST --data-binary "{\"payload\": { \"branch\": \"$CIRCLE_BRANCH\", \"status\": \"success\" } }" https://webhooks.datocms.com/1cd0c86d1a/deploy-results'
          when: on_success
    
workflows:
  version: 2
  main:
    jobs:
      - build-deploy:
          filters:
            branches:
              only: main